### ISSUE TITLE
Meta attributes

### ISSUE THREAD

**Issue by uroybd** [oleeskild/digitalgarden#31]
This is an easy feature to implement. Here's what I thought about it (and used it already):

A key for metatags (e.g. `dg-meta-tags`) with this convention:

 ```yaml
dg-meta-tags:
  description: "some description"
  "og:image": "https://imagelink...."
```
Then we can iterate on it and use the key as the `name` and value as the `content` and generate meta tags in the head.
